name: voc_project
channels:
  - conda-forge
dependencies: #Remember to add pytest
  - python=3.8
  - pip
  - pip:
    - pandas
    - matplotlib
    - boto3
    - datasets
    - flask
    - flake8
    - gensim
    - ipykernel==6.16.0
    - joblib==1.2.0
    - jupyter
    - nltk==3.7
    - numpy
    - pickle5
    - pickleshare==0.7.5
    - pyLDAvis
    - pillow==9.2.0
    - pytest
    - regex==2022.9.13
    - scikit-learn
    - seaborn==0.12.0
    - sklearn
    - syspend
    - transformers==4.26.1
    - tqdm
    - torch
    - torchaudio
    - torchvision
    - xgboost
