name: voc_project
channels:
  - conda-forge
dependencies:
  - flask
  - flask8
  - gensim
  - numpy
  - nltk=3.7
  - matplotlib
  - python=3.8
  - pandas
  - tqdm
  - transformers=4.26.1
  - sklearn
  - scikit-learn