name: voc_project
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - flask
    - flake8
    - gensim
    - numpy
    - nltk==3.7
    - tqdm
    - transformers==4.26.1
    - sklearn
    - xgboost
    - scikit-learn