name: voc_project
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - datasets
    - flask
    - flake8
    - gensim
    - joblib==1.2.0
    - nltk==3.7
    - pickle5
    - pickleshare==0.7.5
    - pillow==9.2.0
    - regex==2022.9.13
    - scikit-learn
    - seaborn==0.12.0
    - sklearn
    - transformers==4.26.1
    - tqdm
    - xgboost
    - scikit-learn
