flask:
  model_type: BERT #NON-BERT
  model_name : roberta-base
  num_classes : 2
  model_path : sentimental_analysis/bert/models/roberta_base_sentimental_gpu_non_trainer_latest.pt
  max_len : 64
  THRESHOLD : 0.6148
  
