flask:
  sentimental_analysis:
    model_name : roberta-large
    num_classes : 2
    max_len : 64
    model_path : sentimental_analysis/bert/models/roberta_large_sentimental.pt
    THRESHOLD : 0.8324
  topic_modelling:
    model_name : non_bert
    topic_modelling_dir: topic_modelling/non_bert
    config_path: topic_modelling/non_bert/non_bert_topic_modelling_config.yml
  historic_trend:
    data_path : data/LDA_10_topics_labelled.csv


  
