model:
  model_name: 'LDA-base'
  num_of_topics: 14
  num_top_words: 20
  num_top_documents: 8
  export_topics: True
  coherence_measure: 'c_v'
  replace_stop_words_list: 
  include_words: ['quality', 'taste', 'tasty', 'nice', 'good', 'great', 'amazon', 'year', 'month', 'day', 'order', 'product']
  exclude_words: []
  root_word_option: 2
  remove_stop_words: True
  lower_case: True
  word_form: ['noun', 'adjective']
  ngrams_start: 1
  ngrams_end: 2
  max_doc: 0.95
  min_doc: 5
  data_folder: data/reviews.csv 
  train_output_path: train_output/topic_14
  test_output_path: test_output/topic_14
  log_path: logs/topic_14.log
  train: True
  test: True
  pickled_model: 
  topic_label: 