model:
  model_name:  'distilbert-base-uncased' #'bert-large-uncased' #'distilbert-base-uncased' #'roberta-large' #'roberta-base' #'bert-base-uncased' 
  n_classes: 2
  max_len: 64
  batch_size: 32
  epochs: 1
  learning_rate: 1e-5
  epsilon: 1e-8
  train_val_percentage: 0.9 
  train_on_full_data: False
  data_folder: data/reviews.csv
  model_path: models/distilbert_base_sentimental.pt
  log_path: logs/distilbert_base__sentimental.log
  plot_path: plots/distilbert_base__sentimental
  noOfKFolds: 5