model:
  model_name:  'distilbert-base-uncased' #'bert-large-uncased' #'distilbert-base-uncased' #'roberta-large' #'roberta-base' #'bert-base-uncased' 
  n_classes: 2
  max_len: 64 #512: GPU Put list
  batch_size: 32
  epochs: 1
  learning_rate: 1e-5
  epsilon: 1e-8
  train_val_percentage: 0.9 #80%
  #test_size_percentage : 0.5 #50%
  #num_warmup_steps: 0
  train_on_full_data: False
  data_folder: data/reviews.csv
  model_path: models/bert_large_sentimental_non_trainer_latest_temp.pt
  log_path: logs/bert_large_sentimental_non_trainer_latest_temp.log
  plot_path: plots/bert_large_sentimental_non_trainer_roc_curve.png
  trainer: False
  noOfKFolds: 5