model:
  model_name: 'bert-large-uncased' # 'bert-base-uncased'
  n_classes: 2
  max_len: 64 #512: GPU Put list
  batch_size: 32
  epochs: 1
  learning_rate: 1e-5
  epsilon: 1e-8
  #num_warmup_steps: 0
  train_on_full_data: False
  data_folder: data/reviews.csv
  model_path: models/bert_large_largesentimental_non_trainer_latest.pt
  log_path: logs/bert_large_sentimental_non_trainer_latest.log 
  trainer: False