model:
<<<<<<< HEAD
  model_name: 'bert-base-uncased'
  n_classes: 2
  max_len: 64 #512 need to use GPU
=======
  model_name:  'distilbert-base-uncased' #'bert-large-uncased' #'distilbert-base-uncased' #'roberta-large' #'roberta-base' #'bert-base-uncased' 
  n_classes: 2
  max_len: 64 #512: GPU Put list
>>>>>>> 054fc082e5b4f198ac41086f2c25cb5f3f3d9060
  batch_size: 32
  epochs: 1
  learning_rate: 1e-5
  epsilon: 1e-8
<<<<<<< HEAD
  #num_warmup_steps: 0
  #train_on_full_data: True
  data_path: data
  train_file: reviews.csv
  #dev_file: test.csv
  # for_pred_path: for_pred_cd.csv
  # pred_path: pred_cd.csv
  model_path: models
  log_path: logs/bert_sentimental.log
=======
  train_val_percentage: 0.9 #80%
  #test_size_percentage : 0.5 #50%
  #num_warmup_steps: 0
  train_on_full_data: False
  data_folder: data/reviews.csv
  model_path: models/distilbert_base_sentimental_non_trainer_latest_temp.pt
  log_path: logs/distilbert_base__sentimental_non_trainer_latest_temp.log
  plot_path: plots/distilbert_base__sentimental_non_trainer
  trainer: False
  noOfKFolds: 5
>>>>>>> 054fc082e5b4f198ac41086f2c25cb5f3f3d9060
