model_0:
  model_name: 'sentence-transformers-key-bigram'
  embedding_model: SentenceTransformer('all-MiniLM-L12-v2')
  dim_reduction_model: None
  clustering_model: None
  vectorizer_params: {'min_df': 1, 'max_df': 1.0, "ngram_range": 2}
  ctfidf_params: {"bm25_weighting": True, "reduce_frequent_words": True}
  representation_model: KeyBERTInspired()
  min_topic_size: 30

model_1:
  model_name: 'sentence-transformers-key-unigram'
  embedding_model: SentenceTransformer('all-MiniLM-L12-v2')
  dim_reduction_model: None
  clustering_model: None
  vectorizer_params: {'min_df': 1, 'max_df': 1.0, "ngram_range": 1}
  ctfidf_params: {"bm25_weighting": True, "reduce_frequent_words": True}
  representation_model: KeyBERTInspired()
  min_topic_size: 30

model_2:
  model_name: 'bert-base-uncased-key-unigram'
  embedding_model: pipeline("feature-extraction", model="bert-base-uncased")
  dim_reduction_model: None
  clustering_model: None
  vectorizer_params: {'min_df': 1, 'max_df': 1.0, "ngram_range": 1}
  ctfidf_params: {"bm25_weighting": True, "reduce_frequent_words": True}
  representation_model: KeyBERTInspired()
  min_topic_size: 30

model_3:
  model_name: 'bert-base-uncased-unigram'
  embedding_model: pipeline("feature-extraction", model="bert-base-uncased")
  dim_reduction_model: None
  clustering_model: None
  vectorizer_params: {'min_df': 1, 'max_df': 1.0, "ngram_range": 1}
  ctfidf_params: {"bm25_weighting": True, "reduce_frequent_words": True}
  representation_model: None
  min_topic_size: 30

model_4:
  model_name: 'sentence-transformers-key-bigram-v2'
  embedding_model: SentenceTransformer('all-MiniLM-L12-v2')
  dim_reduction_model: None
  clustering_model: None
  vectorizer_params: {'min_df': 1, 'max_df': 1.0, "ngram_range": 2}
  ctfidf_params: {"bm25_weighting": True, "reduce_frequent_words": False}
  representation_model: KeyBERTInspired()
  min_topic_size: 30

data_folder: data/reviews.csv
image_folder: image/
log_path: logs/ 